### ISSUE TITLE
Repository with examples

### ISSUE THREAD

**Issue by ruzickap** [telekom/das-schiff#3]
Hello guys.

I really like the [way](https://github.com/telekom/das-schiff#das-schiff-layered-repo) how you described the structure of your repositories - good work.

Would it be possible to add more examples - ideally if you can include the directory structure with some examples as part of this project?

It would be interesting+inspiring to see how you are using Flux v2 with dependencies ([DependsOn](https://fluxcd.io/docs/components/kustomize/kustomization/#specification)), overlays, [variables](https://fluxcd.io/docs/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta1.PostBuild), sops in the `cluster-components`.

I can imagine some k8s components (like cert-manager, monitoring) may be on all clusters, others my be only on prod clusters (resource limits) and every customer/provider may have different requirements for  components/applications.

I would be handy to see how you are dealing with these requirements on real examples...

I can find some "basic" examples of such flux repository inside the flux project ([flux2-multi-tenancy](https://github.com/fluxcd/flux2-multi-tenancy), [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example)), but these examples are really simple comparing to your directory layout.

Thank you...

**Comment by Cellebyte** [comment]
@ruzickap 

the structure grows with the needs.
Applications which should be on all clusters are inside the environments. So that we can keep track of versions between them.
We tried it with a multi branch solution but this was not practical due to the huge differences between the environments. So we added some kind of layers. Each rootdir houses a separate layer.


## This was the approach we initially followed

![ABD26707-6B68-46E5-9672-C6BC65D5B7D6](https://user-images.githubusercontent.com/16540824/117356503-16839300-aeb4-11eb-8fcb-6287caf174ba.png)

**Comment by ruzickap** [comment]
I do understand the diagram, but seeing the example as code would help...

See you

**Comment by vukg** [comment]
The directory with examples is now available: https://github.com/telekom/das-schiff/tree/main/cluster-components
